name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION_REF: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    strategy:
        matrix:
          include:
            - env: sherbet_pico
              bin_ext: uf2

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build ${{ matrix.env }} env
      run: |
        pio run -e ${{ matrix.env }}
        mkdir -p ${{ matrix.env }}
        cp .pio/build/${{ matrix.env }}/firmware.${{ matrix.bin_ext }} ${{ matrix.env }}/${{ matrix.env }}-${{ env.VERSION_REF }}.${{ matrix.bin_ext }}

    - name: Publish ${{ matrix.env }} artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.VERSION_REF }}-${{ matrix.env }}.${{ matrix.bin_ext }}
        path: ${{ matrix.env }}/${{ matrix.env }}-${{ env.VERSION_REF }}.${{ matrix.bin_ext }}

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: ${{ matrix.env }}/${{ matrix.env }}-${{ env.VERSION_REF }}.${{ matrix.bin_ext }}